# general settings
name: detilt
model_type: UnetModel
scale: 1
num_gpu: 1
manual_seed: 42
padding_size: 16
task: detilt

# dataset and data loader settings
datasets:
  train:
    task: detilt
    name: Turbulence
    type: TurbImageDataset
    dataroot: /media/mayue/Data_8T_D/Projects/CVs_Datasets/static_new/train_static
    filename_tmpl: '{}'
    io_backend:
      # type: lmdb
      type: disk
    turb_size: 256
    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: false




  val_1:
    task: test
    name: Turb_test
    type: TurbImageDataset
    dataroot: /media/mayue/Data_8T_D/Projects/CVs_Datasets/static_new/test_static
    turb_size: 256
    gt_size: 256
    io_backend:
      type: disk


# network structures
network_g:
  type: Unet
  inp_channels: 3
  out_channels: 2
  dim: 48
  num_blocks: [1,2,2,1]
  num_refinement_blocks: 1
  channel_heads: [1,2,4,8]
  spatial_heads: [1,2,4,8]
  overlap_ratio: [0.5,0.5,0.5,0.5]
  window_size: 8
  spatial_dim_head: 16
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  scale: 1

# path
path:
  resume_state: ~
  visualization: /media/mayue/Data_8T_D/Projects/ZhangXiao/Unet/experiments/Unet_deblur/visualization

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-6
    betas: [0.9, 0.99]

  scheduler:
    type: CosineContinousAnnealingRestartCyclicLR
    periods: [20000, 200000,300000]
    restart_weights: [1,1,1]
    eta_mins: [0.0001,0.00005,0.00001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 0.2
    reduction: mean
  tilt_field_opt:
    type: CharbonnierLoss
    loss_weight: 0.8
    reduction: mean
# validation settings
val:
  val_freq: !!float 3e5
  save_img: True
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    # project: ~
    # resume_id: ~
    project: Turb_remove
    resume_id:
    entity: xpixel-ntire2022

# dist training settings
dist_params:
  backend: nccl
  port: 29500
