# general settings
name: deblur
model_type: XRestormerModel
scale: 1
num_gpu: 1
manual_seed: 123
padding_size: 16
task: deblur
# dataset and data loader settings
datasets:
  train:
    task: deblur
    name: Turbulence
    type: TurbImageDataset
    dataroot: /media/mayue/Data_8T_D/Projects/CVs_Datasets/static_new/train_static
    filename_tmpl: '{}'
    io_backend:
      # type: lmdb
      type: disk
    turb_size: 256
    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: false



  val_1:
    task: test
    name: TurbTest
    type: TurbImageDataset
    dataroot: /media/mayue/Data_8T_D/Projects/CVs_Datasets/static_new/test_static
    turb_size: 256
    gt_size: 256
    io_backend:
      type: disk


# network structures
network_g:
  type: XRestormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [1,2,2,1]
  num_refinement_blocks: 1
  channel_heads: [1,2,4,8]
  spatial_heads: [1,2,4,8]
  overlap_ratio: [0.5,0.5,0.5,0.5]
  window_size: 8
  spatial_dim_head: 16
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  scale: 1

# path
path:
  resume_state: ~
  visualization: /media/mayue/Data_8T_D/Projects/ZhangXiao/X-Restormer/experiments/xrestormer_deblur/visualization

path:
  strict_load_g: false
  resume_state: ~

# training settings
train:

  optim_g:
    type: AdamW
    lr: !!float 1e-6
    betas: [0.9, 0.99]

  scheduler:
    type: CosineContinousAnnealingRestartCyclicLR
    periods: [20000, 480000,500000]
    restart_weights: [1,1,1]
    eta_mins: [0.0001,0.00005,0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    # type: L1Loss
    loss_weight: 1.0
    reduction: mean

  MS_SSIM_opt:
    # type: MSSSIM
    # window_size: 32
    # size_average: True
    # channel: 3
    type: ReconstructPerceptualLoss
    loss_weight: 0.1

  # perceptual_opt:
  #   type: PerceptualLoss


# validation settings
val:
  val_freq: !!float 1e5
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    # project: ~
    # resume_id: ~
    project: backbone
    resume_id:
    entity: xpixel-ntire2022

# dist training settings
dist_params:
  backend: nccl
  port: 29500

