# general settings
name: deblur
model_type: XRestormerModel
scale: 1
num_gpu: 1
manual_seed: 123
padding_size: 16
task: deblur
# dataset and data loader settings
datasets:
  train:
    task: deblur
    name: Turbulence
    type: TurbImageDataset
    dataroot: /media/mayue/Data_8T_D/Projects/CVs_Datasets/static_new/train_static
    filename_tmpl: '{}'
    io_backend:
      # type: lmdb
      type: disk
    turb_size: 512
    gt_size: 512
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
    pin_memory: false



  val_1:
    task: test
    name: TurbTest
    type: TurbImageDataset
    dataroot: /media/mayue/Data_8T_D/Projects/CVs_Datasets/static_new/test_static
    turb_size: 512
    gt_size: 512
    io_backend:
      type: disk




# network structures
network_g:
  type: NAFNetLocal
  width: 32
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]

# path
path:
  strict_load_g: false
  resume_state: ~

# training settings
train:

  optim_g:
    type: AdamW
    lr: !!float 1e-6
    betas: [0.9, 0.99]

  scheduler:
    type: CosineContinousAnnealingRestartCyclicLR
    periods: [20000, 280000,300000]
    restart_weights: [1,1,1]
    eta_mins: [0.0001,0.00005,0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    # type: L1Loss
    loss_weight: 0.9
    reduction: mean

  # MS_SSIM_opt:
  #   type: MSSSIM
  #   window_size: 32
  #   size_average: True
  #   channel: 3
    # type: Lpips_loss
    # loss_weight: 0.1


# validation settings
val:
  val_freq: !!float 1e5
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    # project: ~
    # resume_id: ~
    project: backbone
    resume_id:
    entity: xpixel-ntire2022

# dist training settings
dist_params:
  backend: nccl
  port: 29500
